[build]
  command = "npm run build"
  publish = "public"

# Edge Function فقط برای مسیر relay فعال شود
[[edge_functions]]
  function = "relay"
  path = "/api/v1/chat/conversation/authenticated"

[[edge_functions]]
  function = "relay"
  path = "/api/v1/chat/conversation/authenticated/*"
